#!/bin/bash
set -e

echo "Updating Packages"
#Clean Yum Cache
yum clean all
rm -rf /var/cache/yum

#Download the latest VitalPBX's repo of Version 2
rm -rf /etc/yum.repos.d/vitalpbx.repo
wget -P /etc/yum.repos.d/ https://raw.githubusercontent.com/VitalPBX/v2-to-v3-migration/master/resources/vitalpbx.repo

#Do the VitalPBX update
yum update vitalpbx -y

# Handle incompatibility issue with old Sonata Recordings
INSTALL_SR=no
if rpm -qa | grep sonata-recordings  2>&1 > /dev/null; then
  INSTALL_SR=yes
fi

# Remove this package because generates conflicts with php-mysqlnd. This will uninstall sonata recordings package also
yum remove php-mysql -y

echo "Update MariaDB"
rm -rf /etc/yum.repos.d/mariadb.repo
wget -P /etc/yum.repos.d/ https://raw.githubusercontent.com/VitalPBX/v2-to-v3-migration/master/resources/mariadb.repo

# Clean Cache
yum clean all
rm -rf /var/cache/yum

rm -rf /etc/my.cnf.d/ombutel.cnf
rm -rf /etc/my.cnf.d/vitalpbx.cnf
wget -P /etc/my.cnf.d/ https://raw.githubusercontent.com/VitalPBX/VPS/vitalpbx-3/resources/vitalpbx.cnf

systemctl stop asterisk
systemctl stop mariadb
yum install MariaDB-server MariaDB-client MariaDB-common MariaDB-compat -y
systemctl enable mariadb
systemctl start mariadb > /dev/null 2>&1
mysql_upgrade

# Delete old baseplan before migrating
rm -rf /etc/asterisk/ombutel/extensions__20-baseplan.conf

echo "Installing VitalPBX 3"
#Download the latest VitalPBX's repo of Version 3
rm -rf /etc/yum.repos.d/vitalpbx.repo
wget -P /etc/yum.repos.d/ https://raw.githubusercontent.com/VitalPBX/VPS/vitalpbx-3/resources/vitalpbx.repo

# Clean Cache
yum clean all
rm -rf /var/cache/yum

#Update the IonCube and PHP first
yum update ioncube-loader -y
yum update php -y
systemctl reload-or-restart httpd

#Update VitalPBX
yum update vitalpbx -y

#Install Sonata Recordings if needed
if [ $INSTALL_SR = "yes" ]; then
  yum install sonata-recordings -y
fi

#do a full update
yum -y update

#Reinstall the VitalPBX add-ons
CORE=("vitalpbx" "vitalpbx-asterisk-configs" "vitalpbx-monitor" "vitalpbx-sounds" "vitalpbx-sounds-es" "vitalpbx-themes", "vitalpbx-fail2ban-config", "vitalpbx-geo-firewall")
rm -f /tmp/addons.txt
touch /tmp/addons.txt
rpm -qa --qf "%{NAME}\n" | grep vitalpbx | while read -r package ; do
   if [[ ! " ${CORE[@]} " =~ " ${package} " ]]; then
     echo ${package} >> /tmp/addons.txt
   fi
done

# If there are any add-on installed then reinstall them
if [ -s /tmp/addons.txt ]; then
  yum -y reinstall $(cat /tmp/addons.txt)
fi

# Force to start setup service before reboot to apply some additional changes
rm -rf /var/lib/vitalpbx/dbsetup-done
systemctl enable vpbx-setup

#Remove the system
echo "Rebooting System"
reboot
