#!/bin/bash
set -e

echo "Updating Packages"
#Clean Yum Cache
yum clean all
rm -rf /var/cache/yum

#Download the latest VitalPBX's repo of Version 2
rm -rf /etc/yum.repos.d/vitalpbx.repo
wget -P /etc/yum.repos.d/ https://raw.githubusercontent.com/VitalPBX/VPS/master/resources/vitalpbx.repo

#Do a full update
yum -y update

echo "Installing VitalPBX 3"
#Download the latest VitalPBX's repo of Version 3
rm -rf /etc/yum.repos.d/vitalpbx.repo
wget -P /etc/yum.repos.d/ https://raw.githubusercontent.com/VitalPBX/VPS/vitalpbx-3/resources/vitalpbx.repo

#Update the IonCube and PHP first
yum update php -y
yum update ioncube-loader -y
systemctl reload-or-restart httpd

#Install MariaDB (MySQL)
rm -rf /etc/my.cnf.d/ombutel.cnf
rm -rf /etc/my.cnf.d/vitalpbx.cnf
wget -P /etc/my.cnf.d/ https://raw.githubusercontent.com/VitalPBX/VPS/vitalpbx-3/resources/vitalpbx.cnf
yum install MariaDB-server MariaDB-client MariaDB-common MariaDB-compat mariadb-connector-odbc -y
systemctl enable mariadb
systemctl restart mariadb > /dev/null 2>&1
systemctl restart mariadb > /dev/null 2>&1
mysql_upgrade

#Clean cache
yum clean all
rm -rf /var/cache/yum

#Update VitalPBX
yum update vitalpbx -y

#do a full update
yum -y update

#Remove the system
echo "Rebooting System"
reboot
